# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: absensi.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rabsensi.proto\"x\n\x07\x41\x62sensi\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rnama_karyawan\x18\x02 \x01(\t\x12\x0f\n\x07tanggal\x18\x03 \x01(\t\x12\x0e\n\x06\x64ivisi\x18\x04 \x01(\t\x12\x13\n\x0bwaktu_masuk\x18\x05 \x01(\t\x12\x14\n\x0cwaktu_keluar\x18\x06 \x01(\t\"\x17\n\tAbsensiId\x12\n\n\x02id\x18\x01 \x01(\t\"D\n\x0e\x41\x62sensiRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x15\n\rnama_karyawan\x18\x02 \x01(\t\x12\x0f\n\x07tanggal\x18\x03 \x01(\t2\xb6\x02\n\x0e\x41\x62sensiService\x12*\n\x12\x43reateAbsensiMasuk\x12\x08.Absensi\x1a\x08.Absensi\"\x00\x12+\n\x13\x43reateAbsensiPulang\x12\x08.Absensi\x1a\x08.Absensi\"\x00\x12%\n\rUpdateAbsensi\x12\x08.Absensi\x1a\x08.Absensi\"\x00\x12,\n\x0bReadAbsensi\x12\x0f.AbsensiRequest\x1a\x08.Absensi\"\x00\x30\x01\x12,\n\rDeleteAbsensi\x12\x0f.AbsensiRequest\x1a\x08.Absensi\"\x00\x12H\n\'SearchAbsensiIdByNamaKaryawanAndTanggal\x12\x0f.AbsensiRequest\x1a\n.AbsensiId\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'absensi_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ABSENSI']._serialized_start=17
  _globals['_ABSENSI']._serialized_end=137
  _globals['_ABSENSIID']._serialized_start=139
  _globals['_ABSENSIID']._serialized_end=162
  _globals['_ABSENSIREQUEST']._serialized_start=164
  _globals['_ABSENSIREQUEST']._serialized_end=232
  _globals['_ABSENSISERVICE']._serialized_start=235
  _globals['_ABSENSISERVICE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
